name: PassivePhantoms
version: 1.2.3
main: PassivePhantoms
api-version: 1.21
description: Makes phantoms passive until they are attacked by a player

commands:
  passivephantoms:
    description: Reload the PassivePhantoms configuration
    usage: /<command> reload
    permission: passivephantoms.reload 
